version: '3.8'

services:
  login-service:
    build:
      context: ./login-service
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASS: mypassword
      DB_HOST: bankstack-db
      DB_NAME: bankstack
    volumes:
      - ./login-service:/app  # ✅ For live reload in dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  # ✅ Dev mode only
    depends_on:
      - bankstack-db

  bankstack-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: bankstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  account-service:
    build: ./account-service
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=bankstack-db
      - DB_NAME=bankstack
      - DB_USER=postgres
      - DB_PASS=mypassword
      - JWT_SECRET=bankstack-secret-key
      - JWT_ALGORITHM=HS256
    volumes:
      - ./account-service:/app
    depends_on:
      - bankstack-db

volumes:
  pgdata:

